### ISSUE TITLE
Http status code issue

### ISSUE THREAD

**Issue by tripathi-atul** [dannwebster/experiment4j#21]
Http status code issue: When we are getting different response code from candidate or control like 500, experiment 4j should provide the option to set the same status code in response. As of now i is 200 since experiment4j will be successful while control/candidate not. Please suggest.

**Comment by dannwebster** [comment]
Can you provide a code sample of how this is being used? I would not expect for experiment4j to be aware of any HTTP specific classes (it should be generic across frameworks/usecases). 

If the candidate and control are mutating state for the Http Response object, I would expect them to provide or modify the response code.

Can you provide a code snippet or gist that helps me understand the usecase better?

Thanks,

**Comment by tripathi-atul** [comment]
I have handled this scenario from my code itself, i have another query which i will add as different issues.
